<script setup lang="ts">
import { Bot, BookOpen, FilePlus2, Loader2, RefreshCw } from 'lucide-vue-next'
import { friendlyCodexExecError, runCodexExec } from '~/composables/useCodexShell'
import { renderMarkdown } from '~/utils/markdown'

const props = defineProps<{
  projectPath: string
}>()

const fs = useTauriFs()
const projects = useProjectsStore()
const { notify } = useNotifications()
const { appendHistory } = useVindicterJson()
const loading = ref(false)
const analyzing = ref(false)
const generatingReadme = ref(false)
const showAnalysis = ref(false)
const readme = ref('')
const error = ref<string | null>(null)
const fileName = ref('README.md')
const readmeFound = ref(false)
const aiSummaryMarkdown = ref('')
const aiSummaryError = ref<string | null>(null)

const readmeHtml = computed(() => {
  return renderMarkdown(readme.value)
})

async function loadReadme() {
  loading.value = true
  error.value = null
  readme.value = ''
  readmeFound.value = false
  try {
    const candidates = ['README.md', 'Readme.md', 'readme.md']
    for (const name of candidates) {
      const path = `${props.projectPath}/${name}`
      if (await fs.exists(path).catch(() => false)) {
        fileName.value = name
        readme.value = await fs.readTextFile(path)
        readmeFound.value = true
        return
      }
    }
    fileName.value = 'README.md'
    error.value = 'No README.md file found in this project.'
  }
  catch (e: any) {
    error.value = e?.message ?? 'Failed to read README.md.'
  }
  finally {
    loading.value = false
  }
}

function projectDirectoryName(path: string) {
  return path.replace(/[\\/]+$/, '').split(/[\\/]/).pop() || 'Project'
}

function inferPackageScripts(packageJson: any) {
  if (!packageJson?.scripts || typeof packageJson.scripts !== 'object') return []
  return Object.entries(packageJson.scripts)
    .slice(0, 8)
    .map(([name, command]) => `- \`${name}\`: \`${String(command)}\``)
}

async function generateReadme() {
  generatingReadme.value = true
  try {
    const project = projects.projects.find(item => item.absolutePath === props.projectPath) ?? projects.activeProject
    const entries = await fs.readDir(props.projectPath).catch(() => [])
    const names = entries.slice(0, 12).map(entry => `- ${entry.isDir ? 'Directory' : 'File'}: \`${entry.name}\``)
    const packagePath = `${props.projectPath}/package.json`
    const packageRaw = await fs.exists(packagePath).catch(() => false)
      ? await fs.readTextFile(packagePath).catch(() => '')
      : ''
    const packageJson = packageRaw ? JSON.parse(packageRaw) : null
    const scripts = inferPackageScripts(packageJson)

    const title = project?.name || packageJson?.name || projectDirectoryName(props.projectPath)
    const description = project?.description || packageJson?.description || 'Project workspace managed with Vindicter.'
    const generatedAt = new Date().toISOString().slice(0, 10)
    const markdown = [
      `# ${title}`,
      '',
      description,
      '',
      '## Overview',
      `- Project code: ${project?.code ?? 'Not set'}`,
      `- Generated by Vindicter: ${generatedAt}`,
      '',
      ...(names.length ? ['## Project Structure', ...names, ''] : []),
      ...(scripts.length ? ['## Scripts', ...scripts, ''] : []),
      '## Notes',
      '- Keep this README updated as the project evolves.',
      '- Use Vindicter sprint reports and changelog updates to preserve delivery context.',
      '',
    ].join('\n')

    await fs.writeTextFile(`${props.projectPath}/README.md`, markdown)
    await appendHistory(props.projectPath, {
      action: 'project:docs_updated',
      actor: 'local',
      payload: { name: 'README.md', operation: 'generated' },
    }).catch(() => {})
    notify('README.md generated.', 'success')
    await loadReadme()
  }
  catch (e: any) {
    notify(e?.message ?? 'Could not generate README.md.', 'error')
  }
  finally {
    generatingReadme.value = false
  }
}

async function askAIAboutProject() {
  analyzing.value = true
  showAnalysis.value = true
  aiSummaryError.value = null
  aiSummaryMarkdown.value = ''
  try {
    const project = projects.projects.find(item => item.absolutePath === props.projectPath) ?? projects.activeProject
    const prompt = `You are helping inside Vindicter. Analyze this local project for the user.

Project name: ${project?.name ?? projectDirectoryName(props.projectPath)}
Project path: ${props.projectPath}
README detected: ${readmeFound.value ? fileName.value : 'No README.md found'}

Inspect the repository in read-only mode. Prefer README context when present, then use nearby project files such as package manifests, app entry points, configuration, and Vindicter project data.

Return concise markdown with these headings:
## What this project is
## Stack and structure
## Important files
## Risks or gaps
## Suggested next steps

Do not edit files. Keep the answer practical and grounded in observable files.`

    const result = await runCodexExec({
      projectPath: props.projectPath,
      prompt,
      model: 'Codex CLI default (project info)',
      reasoningEffort: 'medium',
      sandbox: 'read-only',
    })
    const response = [result.stdout, result.stderr].filter(Boolean).join('\n').trim()
    if (result.code !== 0) throw new Error(response || 'AI analysis failed.')
    aiSummaryMarkdown.value = response || 'Codex finished without returning a project summary.'
  }
  catch (e: any) {
    aiSummaryError.value = friendlyCodexExecError(e?.message ?? e)
  }
  finally {
    analyzing.value = false
  }
}

watch(() => props.projectPath, loadReadme, { immediate: true })
</script>

<template>
  <div class="space-y-4">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex items-center gap-2">
        <BookOpen class="size-4 text-indigo-300" />
        <div>
          <h3 class="text-sm font-semibold text-[var(--text)]">Project Info</h3>
          <p class="text-xs text-[var(--text-muted)]">{{ fileName }}</p>
        </div>
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <button
          class="inline-flex items-center gap-1.5 rounded-lg border border-indigo-500/25 bg-indigo-500/10 px-3 py-2 text-xs font-medium text-indigo-200 transition-colors hover:bg-indigo-500/15 disabled:opacity-50"
          :disabled="analyzing"
          @click="askAIAboutProject"
        >
          <Loader2 v-if="analyzing" class="size-3.5 animate-spin" />
          <Bot v-else class="size-3.5" />
          Ask AI about the whole project
        </button>
        <button
          v-if="!loading && !readmeFound"
          class="inline-flex items-center gap-1.5 rounded-lg border border-emerald-500/25 bg-emerald-500/10 px-3 py-2 text-xs font-medium text-emerald-200 transition-colors hover:bg-emerald-500/15 disabled:opacity-50"
          :disabled="generatingReadme"
          @click="generateReadme"
        >
          <Loader2 v-if="generatingReadme" class="size-3.5 animate-spin" />
          <FilePlus2 v-else class="size-3.5" />
          Generate README file
        </button>
        <button
          class="p-2 rounded-lg border border-[var(--border)] text-[var(--text-muted)] hover:text-[var(--text)] hover:bg-white/[0.05] transition-colors"
          title="Refresh README"
          :disabled="loading"
          @click="loadReadme"
        >
          <RefreshCw class="size-3.5" :class="loading ? 'animate-spin' : ''" />
        </button>
      </div>
    </div>

    <div v-if="loading" class="py-12 text-center text-sm text-[var(--text-muted)]">
      Loading README...
    </div>
    <div v-else-if="error" class="rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3">
      <p class="text-sm text-amber-200/80">{{ error }}</p>
      <button
        v-if="!readmeFound"
        class="mt-3 inline-flex items-center gap-1.5 rounded-lg border border-emerald-500/25 bg-emerald-500/10 px-3 py-2 text-xs font-medium text-emerald-200 transition-colors hover:bg-emerald-500/15 disabled:opacity-50"
        :disabled="generatingReadme"
        @click="generateReadme"
      >
        <Loader2 v-if="generatingReadme" class="size-3.5 animate-spin" />
        <FilePlus2 v-else class="size-3.5" />
        Generate README file
      </button>
    </div>
    <article
      v-else
      class="markdown-body rounded-xl border border-[var(--border)] bg-[var(--bg-card)] px-5 py-4"
      v-html="readmeHtml"
    />

    <GlassModal v-model="showAnalysis" title="AI Project Analysis" max-width="xl">
      <div v-if="analyzing" class="flex items-center gap-2 rounded-lg border border-[var(--border)] bg-black/20 px-4 py-3 text-sm text-[var(--text-muted)]">
        <Loader2 class="size-4 animate-spin text-indigo-300" />
        Analyzing project context...
      </div>
      <div v-else-if="aiSummaryError" class="rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200/85">
        {{ aiSummaryError }}
      </div>
      <article
        v-else
        class="markdown-body rounded-lg border border-[var(--border)] bg-black/20 px-5 py-4"
        v-html="renderMarkdown(aiSummaryMarkdown)"
      />
    </GlassModal>
  </div>
</template>

<style scoped>
.markdown-body :deep(h1) { font-size: 1.5rem; font-weight: 700; color: white; margin-bottom: 0.75rem; }
.markdown-body :deep(h2) { font-size: 1.125rem; font-weight: 650; color: white; margin-top: 1.25rem; margin-bottom: 0.5rem; border-bottom: 1px solid var(--border); padding-bottom: 0.375rem; }
.markdown-body :deep(h3) { font-size: 1rem; font-weight: 600; color: rgba(255,255,255,0.85); margin-top: 1rem; margin-bottom: 0.375rem; }
.markdown-body :deep(p) { color: rgba(255,255,255,0.65); font-size: 0.875rem; line-height: 1.7; margin-bottom: 0.75rem; }
.markdown-body :deep(a) { color: #a5b4fc; text-decoration: underline; text-underline-offset: 2px; }
.markdown-body :deep(ul) { list-style-type: disc; margin-left: 1.25rem; margin-bottom: 0.75rem; }
.markdown-body :deep(ol) { list-style-type: decimal; margin-left: 1.25rem; margin-bottom: 0.75rem; }
.markdown-body :deep(li) { color: rgba(255,255,255,0.65); font-size: 0.875rem; margin-bottom: 0.25rem; }
.markdown-body :deep(code) { font-size: 0.75rem; font-family: monospace; background: rgba(255,255,255,0.1); padding: 0.125rem 0.375rem; border-radius: 0.25rem; color: #c4b5fd; }
.markdown-body :deep(pre) { background: rgba(0,0,0,0.28); border: 1px solid var(--border); border-radius: 0.5rem; padding: 0.875rem; overflow-x: auto; margin-bottom: 0.875rem; }
.markdown-body :deep(pre code) { background: transparent; padding: 0; }
.markdown-body :deep(blockquote) { border-left: 2px solid rgba(99,102,241,0.5); padding-left: 0.875rem; color: rgba(255,255,255,0.5); font-style: italic; }
.markdown-body :deep(table) { width: 100%; border-collapse: collapse; margin-bottom: 0.875rem; font-size: 0.8125rem; }
.markdown-body :deep(th),
.markdown-body :deep(td) { border: 1px solid var(--border); padding: 0.5rem; color: rgba(255,255,255,0.65); }
.markdown-body :deep(th) { color: white; background: rgba(255,255,255,0.05); }
</style>
